CREATE TABLE tblDWebTemp (
    ID INT IDENTITY(1,1) NOT NULL,
    UserId INT NOT NULL,
    CCode INT NOT NULL,
    FarmerCode VARCHAR(20) NOT NULL,
    OldCode VARCHAR(20) NOT NULL,
    Parent VARCHAR(20) NOT NULL,
    DateOf VARCHAR(40) NOT NULL,
    TimeOf VARCHAR(10) NOT NULL,
    SNF DECIMAL(5,1) NOT NULL,
    FAT DECIMAL(5,1) NOT NULL,
    SavedTime DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (ID)
);